/*
 * Copyright 2026 Incident Command Agent contributors
 * SPDX-License-Identifier: Apache-2.0
 */
// GENERATED by `npm run scenarios:validate`. Do not edit by hand.
import s0 from './s01-pushback-tug-contact.json' with { type: 'json' };
import s1 from './s02-catering-truck-door-strike.json' with { type: 'json' };
import s2 from './s03-bird-strike-inspection.json' with { type: 'json' };
import s3 from './s04-lightning-strike-outstation.json' with { type: 'json' };
import s4 from './s05-cargo-door-warning.json' with { type: 'json' };
import s5 from './s06-apu-inop-deferral-temptation.json' with { type: 'json' };
import s6 from './s07-slide-inadvertent-deployment.json' with { type: 'json' };
import s7 from './s08-hydraulic-leak-on-stand.json' with { type: 'json' };
import s8 from './s09-fuel-spill-at-stand.json' with { type: 'json' };
import s9 from './s10-brake-overheat-fdp-squeeze.json' with { type: 'json' };

export const scenarioModules: unknown[] = [s0, s1, s2, s3, s4, s5, s6, s7, s8, s9];
