/*
 * Copyright 2026 Incident Command Agent contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/**
 * Stations (real IATA airports, OurAirports public-domain data) and great-circle distances.
 * `data/airports/stations.json` is generated by `npm run airports:build` and committed.
 */
import stationsFile from '../airports/stations.json' with { type: 'json' };

export interface StationRecord {
  iata: string;
  icao?: string;
  name: string;
  lat: number;
  lon: number;
  country: string;
  region?: string;
  /** Standard-time offset from UTC in minutes (DST applied by `utcOffsetMinutes`). */
  utcStdOffsetMin: number;
}

export const stations: readonly StationRecord[] = (stationsFile as { stations: StationRecord[] }).stations;

const byIata = new Map(stations.map((s) => [s.iata, s]));

export function getStation(iata: string): StationRecord | undefined {
  return byIata.get(iata.toUpperCase());
}

/** EU/EEA member airports (for the EU261 "intra-Community" rule). GB is not EU (UK261 mirrors the tiers). */
export const EU_COUNTRIES = new Set(
  (
    'AT BE BG HR CY CZ DK EE FI FR DE GR HU IE IT LV LT LU MT NL PL PT RO SK SI ES SE ' + // EU 27
    'IS NO LI CH'
  ) // EEA + Switzerland apply Reg. 261/2004
    .split(' '),
);

export function isEuStation(iata: string): boolean {
  const s = getStation(iata);
  return !!s && EU_COUNTRIES.has(s.country);
}

const R_KM = 6371.0088;

/** Haversine great-circle distance between two lat/lon points, km. */
export function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R_KM * Math.asin(Math.min(1, Math.sqrt(a)));
}

/** Great-circle distance between two IATA stations in km (rounded to 1 km). Throws for unknown stations. */
export function distanceKm(a: string, b: string): number {
  if (a === b) return 0;
  const sa = getStation(a);
  const sb = getStation(b);
  if (!sa) throw new Error(`unknown station ${a}`);
  if (!sb) throw new Error(`unknown station ${b}`);
  return Math.round(haversineKm(sa.lat, sa.lon, sb.lat, sb.lon));
}

/** Last Sunday of a month (UTC date), used for the EU summer-time rule. */
function lastSunday(year: number, month: number): number {
  const d = new Date(Date.UTC(year, month + 1, 0));
  d.setUTCDate(d.getUTCDate() - d.getUTCDay());
  return d.getTime();
}

/** UTC offset in minutes at `when` for a station (EU DST: last Sunday in March 01:00 UTC → last Sunday in October). */
export function utcOffsetMinutes(iata: string, when: Date): number {
  const s = getStation(iata);
  const std = s?.utcStdOffsetMin ?? 0;
  const y = when.getUTCFullYear();
  const start = lastSunday(y, 2) + 3_600_000;
  const end = lastSunday(y, 9) + 3_600_000;
  const t = when.getTime();
  const dst = s && s.country !== 'IS' && s.country !== 'TR' && s.country !== 'RU' && t >= start && t < end;
  return std + (dst ? 60 : 0);
}

/** Local wall-clock "HH:MM" at a station for an ISO/Date instant. */
export function localHhMm(iata: string, when: Date): string {
  const local = new Date(when.getTime() + utcOffsetMinutes(iata, when) * 60_000);
  return `${String(local.getUTCHours()).padStart(2, '0')}:${String(local.getUTCMinutes()).padStart(2, '0')}`;
}
