/*
 * Copyright 2026 Incident Command Agent contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/** Renders `tokens.css`: CSS custom properties for both themes (dark is the default "ops room" theme). */
import { hexToRgb } from './contrast';
import {
  colors,
  elevation,
  motion,
  radii,
  spacing,
  typography,
  type ColorScale,
  type ThemeName,
} from './tokens';

const HEADER = `/*
 * Copyright 2026 Incident Command Agent contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by packages/ui-tokens (npm run build -w @ica/ui-tokens). Do not edit by hand.
 */`;

/** `--c-fg: 231 237 243` (channels, for Tailwind alpha) and `--color-fg: #E7EDF3`. */
function colorVars(scale: ColorScale): string[] {
  return Object.entries(scale).flatMap(([name, hex]) => [
    `--c-${name}: ${hexToRgb(hex).join(' ')};`,
    `--color-${name}: ${hex};`,
  ]);
}

function themeVars(theme: ThemeName): string[] {
  return [
    ...colorVars(colors[theme]),
    ...Object.entries(elevation[theme]).map(([k, v]) => `--shadow-${k}: ${v};`),
    `color-scheme: ${theme};`,
  ];
}

function staticVars(): string[] {
  return [
    `--font-sans: ${typography.fontFamily.sans};`,
    `--font-mono: ${typography.fontFamily.mono};`,
    ...Object.entries(typography.scale).flatMap(([k, v]) => [
      `--text-${k}-size: ${v.size}px;`,
      `--text-${k}-line: ${v.lineHeight}px;`,
      `--text-${k}-weight: ${v.weight};`,
    ]),
    ...Object.entries(spacing).map(([k, v]) => `--space-${k.replace('.', '_')}: ${v}px;`),
    ...Object.entries(radii).map(([k, v]) => `--radius-${k}: ${v}px;`),
    ...Object.entries(motion.duration).map(([k, v]) => `--duration-${k}: ${v}ms;`),
    ...Object.entries(motion.easing).map(([k, v]) => `--ease-${k}: ${v};`),
  ];
}

const block = (selector: string, lines: string[], indent = '') =>
  `${indent}${selector} {\n${lines.map((l) => `${indent}  ${l}`).join('\n')}\n${indent}}`;

export function renderTokensCss(): string {
  return [
    HEADER,
    block(':root', staticVars()),
    block(':root,\n[data-theme="dark"]', themeVars('dark')),
    block('[data-theme="light"]', themeVars('light')),
    `@media (prefers-reduced-motion: reduce) {\n${block(
      ':root',
      Object.keys(motion.duration).map((k) => `--duration-${k}: 0ms;`),
      '  ',
    )}\n}`,
    '',
  ].join('\n\n');
}
