/*
 * Copyright 2026 Incident Command Agent contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/**
 * The mock-mode recordings (fictional data): s01 and s04 generated by `npm run fixtures -w @ica/web`, the airborne
 * s11 by `npx tsx evals/scripts/record-mock-turnback.ts`.
 * Each has a scenario, an agent run and its paired baseline run.
 */
import type { RunEvent, Scenario } from '@ica/schema/browser';
import s01Agent from './fixtures/s01.agent.events.json';
import s01Baseline from './fixtures/s01.baseline.events.json';
import s01Scenario from './fixtures/s01.scenario.json';
import s04Agent from './fixtures/s04.agent.events.json';
import s04Baseline from './fixtures/s04.baseline.events.json';
import s04Scenario from './fixtures/s04.scenario.json';
import s11Agent from './fixtures/s11.agent.events.json';
import s11Baseline from './fixtures/s11.baseline.events.json';
import s11Scenario from './fixtures/s11.scenario.json';

export interface Recording {
  scenario: Scenario;
  agent: RunEvent[];
  baseline: RunEvent[];
}

export const RECORDINGS: Recording[] = [
  {
    scenario: s01Scenario as unknown as Scenario,
    agent: s01Agent as unknown as RunEvent[],
    baseline: s01Baseline as unknown as RunEvent[],
  },
  {
    scenario: s04Scenario as unknown as Scenario,
    agent: s04Agent as unknown as RunEvent[],
    baseline: s04Baseline as unknown as RunEvent[],
  },
  {
    // Task 07: the airborne turnback, recorded through the real runtime with the scripted provider
    // (evals/scripts/record-mock-turnback.ts).
    scenario: s11Scenario as unknown as Scenario,
    agent: s11Agent as unknown as RunEvent[],
    baseline: s11Baseline as unknown as RunEvent[],
  },
];

export function recordingFor(scenarioId: string): Recording | undefined {
  return RECORDINGS.find((r) => r.scenario.id === scenarioId);
}
