/*
 * Copyright 2026 Incident Command Agent contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/**
 * The mock-mode recordings (fictional data), generated by `npm run fixtures -w @ica/web`.
 * Each has a scenario, an agent run and its paired baseline run.
 */
import type { RunEvent, Scenario } from '@ica/schema/browser';
import s01Agent from './fixtures/s01.agent.events.json';
import s01Baseline from './fixtures/s01.baseline.events.json';
import s01Scenario from './fixtures/s01.scenario.json';
import s04Agent from './fixtures/s04.agent.events.json';
import s04Baseline from './fixtures/s04.baseline.events.json';
import s04Scenario from './fixtures/s04.scenario.json';

export interface Recording {
  scenario: Scenario;
  agent: RunEvent[];
  baseline: RunEvent[];
}

export const RECORDINGS: Recording[] = [
  {
    scenario: s01Scenario as unknown as Scenario,
    agent: s01Agent as unknown as RunEvent[],
    baseline: s01Baseline as unknown as RunEvent[],
  },
  {
    scenario: s04Scenario as unknown as Scenario,
    agent: s04Agent as unknown as RunEvent[],
    baseline: s04Baseline as unknown as RunEvent[],
  },
];

export function recordingFor(scenarioId: string): Recording | undefined {
  return RECORDINGS.find((r) => r.scenario.id === scenarioId);
}
