/*
 * Copyright 2026 Incident Command Agent contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/** Renders scenarios/public/index.gen.ts: static JSON imports of every scenarios/public/*.json. */
import { readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const PUBLIC_DIR = fileURLToPath(new URL('../public/', import.meta.url));
export const PRIVATE_DIR = fileURLToPath(new URL('../private/', import.meta.url));
export const INDEX_FILE = fileURLToPath(new URL('../public/index.gen.ts', import.meta.url));

export function listJson(dir: string): string[] {
  try {
    return readdirSync(dir)
      .filter((f) => f.endsWith('.json'))
      .sort();
  } catch {
    return [];
  }
}

export function renderIndex(files: string[]): string {
  const header = [
    '/*',
    ' * Copyright 2026 Incident Command Agent contributors',
    ' * SPDX-License-Identifier: Apache-2.0',
    ' */',
    '// GENERATED by `npm run scenarios:validate`. Do not edit by hand.',
  ];
  if (files.length === 0) {
    return [
      ...header,
      '// No public scenarios yet: seeded with the minimal fixture until task 03 adds scenarios/public/*.json.',
      "import s0 from '@ica/schema/fixtures/scenario.minimal.json' with { type: 'json' };",
      '',
      'export const scenarioModules: unknown[] = [s0];',
      '',
    ].join('\n');
  }
  const imports = files.map((f, i) => `import s${i} from './${f}' with { type: 'json' };`);
  return [
    ...header,
    ...imports,
    '',
    `export const scenarioModules: unknown[] = [${files.map((_, i) => `s${i}`).join(', ')}];`,
    '',
  ].join('\n');
}
